version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip install aws-sam-cli
  build:
    commands:
      - cd web-frontend
      - sam build
      - sam package --s3-bucket $ARTIFACTS_BUCKET --output-template-file packaged-template.yaml

artifacts:
  files:
    - web-frontend/packaged-template.yaml