version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip install --upgrade pip
      - pip install -r requirements.txt
  
  pre_build:
    commands:
      - echo Running tests...
      - python -m pytest test_app.py -v --junitxml=pytest_reports.xml --cov=app --cov-report=xml
  
  build:
    commands:
      - echo Build started on `date`
      - sam build
  
  post_build:
    commands:
      - echo Build completed on `date`

reports:
  pytest_reports:
    files:
      - pytest_reports.xml
    file-format: JUNITXML

artifacts:
  files:
    - template.yaml
    - .aws-sam/**/*